- name: Yolo5 EC2s
  hosts: all
  become: yes
  vars:
    ansible_user: ubuntu
  tasks:
    - name: Get AWS_ACCESS_KEY_ID from environment
      set_fact:
        aws_region: "{{ lookup('env', 'AWS_REGION') }}"

    - name: Login to Amazon ECR
      shell: |
        aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin 019273956931.dkr.ecr.{{ aws_region }}.amazonaws.com

    - name: Pull latest Docker image
      docker_image:
        name: "019273956931.dkr.ecr.{{ aws_region }}.amazonaws.com/raoof-images:yolo5-v2-{{ github_run_number }}"
        source: pull

    - name: Stop and remove existing container
      docker_container:
        name: yolo5
        state: absent

    - name: Run new container
      docker_container:
        name: yolo5
        image: "019273956931.dkr.ecr.{{ aws_region }}.amazonaws.com/raoof-images:yolo5-v2-{{ github_run_number }}"
        state: started
        published_ports:
          - "8081:8081"
        env:
          AWS_DEFAULT_REGION: "{{ aws_region }}"
          TELEGRAM_APP_URL: "Raoof-LoadBalancer-1780755932.us-west-1.elb.amazonaws.com"
          SQS_QUEUE_IDENTIFY: "Raoof-AWS-SQS-identify"
          SQS_QUEUE_RESULTS: "Raoof-AWS-SQS-results"
          BUCKET_NAME: "raoofbucket"
          BUCKET_PREFIX: "images"
        restart_policy: always