name: Polybot Microservice Deployment

on:
  push:
    paths:
      - 'polybot/**'
    branches:
      - main




jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo code
        uses: actions/checkout@v2

      - name: Build and push image
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-1'
        run: |
          cd polybot

          # Login to ECR:
          aws ecr get-login-password --region ${{ env.AWS_DEFAULT_REGION }} | docker login --username AWS --password-stdin 019273956931.dkr.ecr.${{ env.AWS_DEFAULT_REGION }}.amazonaws.com

          # Define the base name of the image and the tag separately
          IMAGE_BASE_NAME=polybot-v2
          IMAGE_TAG=${{ github.run_number }}

          # Build the image
          docker build -t ${IMAGE_BASE_NAME}:${IMAGE_TAG} .

          # Tag the image for ECR
          docker tag ${IMAGE_BASE_NAME}:${IMAGE_TAG} 019273956931.dkr.ecr.us-west-1.amazonaws.com/raoof-images:${IMAGE_BASE_NAME}-${IMAGE_TAG}

          # Push the image to ECR
          docker push 019273956931.dkr.ecr.us-west-1.amazonaws.com/raoof-images:${IMAGE_BASE_NAME}-${IMAGE_TAG}
          

